# Generated by Django 5.0.1 on 2024-01-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kuzov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Car_kuzov', to='car.kuzov'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manzil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_location', to='car.locations'),
        ),
        migrations.AlterField(
            model_name='car',
            name='modeli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_model', to='car.car_model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='uzatish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_qutisi', to='car.uzatish'),
        ),
        migrations.AlterField(
            model_name='car',
            name='uzatma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_qutisi', to='car.uzatma'),
        ),
        migrations.AlterField(
            model_name='car',
            name='yoqilgi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_yoqilgisi', to='car.yoqilgi'),
        ),
    ]
